on: [push]

jobs:
  run_docker_file:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - run: cd ..
    - run: ls -a
    - name: Build docker image
      run: docker build . -t test-image
    - name: Run docker image
      run: docker run test-image
      

  